trigger:
- master


variables:
  buildConfiguration: 'Release'


jobs:
- job: Build
  displayName: Build
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: PowerShell@2
    inputs:
      filePath: './build.ps1'
      arguments: '--target CI --configuration $(buildConfiguration)'
